#define SECRET_SSID "IotWifiBridged"
#define SECRET_PASS "Iot-2019"
#define MQTT_USER "mqtt_iotuser"
#define MQTT_PASS "mqttiot.2019"
#define SECRET_MQTT_CLIENT_ID "1883"
#define SECRET_MQTT_HOST "192.168.1.40"
